language: python

python:
   - "3.5"

sudo: false

notifications:
  slack: cs329e-spring-2017:AWsM9A5m1bIn3AFcRRVQEBVl

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install numpy
    - pip install pylint

before_script:
    - uname -a
    - printenv
    - pip list
    - coverage --version
    - pylint   --version

script:
    - date
    - ls -al
<<<<<<< Updated upstream
    - make test
=======
<<<<<<< HEAD
    - make test
=======
    - make test
>>>>>>> b78ad24e185b29e374831200e9394042f6ac2e22
>>>>>>> Stashed changes
